"use client";
import { FormEvent, useEffect, useState } from 'react';
import { Headphones, MessageSquare, RefreshCw } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

export default function SupportPanel() {
  const {user,userData}=useAuth(); const [tickets,setTickets]=useState<any[]>([]); const [deviceId,setDeviceId]=useState('');const [subject,setSubject]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [reply,setReply]=useState<Record<string,string>>({});
  const token=()=>user?.getIdToken(); const load=async()=>{const r=await fetch('/api/support/tickets',{headers:{Authorization:`Bearer ${await token()}`},cache:'no-store'});if(r.ok)setTickets((await r.json()).tickets||[])};
  useEffect(()=>{if(user)void load()},[user]);
  const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const r=await fetch('/api/support/tickets',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({deviceId,subject,message})});const d=await r.json();if(!r.ok)alert(d.error||'Ticket nije kreiran.');else{setDeviceId('');setSubject('');setMessage('');await load()}setBusy(false)};
  const update=async(id:string,status?:string)=>{const body:any={id};if(status)body.status=status;if(reply[id]?.trim())body.message=reply[id].trim();const r=await fetch('/api/support/tickets',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify(body)});if(r.ok){setReply(x=>({...x,[id]:''}));await load()}else alert((await r.json()).error||'Izmjena nije spremljena.')};
  return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={create} className="h-fit rounded-3xl border border-gray-700 bg-gray-900/60 p-6"><h2 className="flex items-center gap-2 text-xl font-bold text-white"><Headphones className="text-blue-400"/> Novi zahtjev</h2><p className="mt-1 text-sm text-gray-400">Podrška je izravno povezana s uređajem.</p>{[['Device ID',deviceId,setDeviceId],['Naslov',subject,setSubject]].map(([l,v,s]:any)=><label key={l} className="mt-4 block text-sm text-gray-400">{l}<input required value={v} onChange={e=>s(e.target.value)} className="mt-2 w-full rounded-xl border border-gray-700 bg-gray-950 p-3 text-white outline-none focus:border-blue-500"/></label>)}<label className="mt-4 block text-sm text-gray-400">Opis<textarea required value={message} onChange={e=>setMessage(e.target.value)} rows={5} className="mt-2 w-full rounded-xl border border-gray-700 bg-gray-950 p-3 text-white outline-none focus:border-blue-500"/></label><button disabled={busy} className="mt-4 w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-50">{busy?'Slanje...':'Otvori ticket'}</button></form>
  <div className="rounded-3xl border border-gray-700 bg-gray-900/60 p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold text-white">Zahtjevi podrške</h2><p className="text-sm text-gray-400">Razgovori i status rješavanja.</p></div><button onClick={load}><RefreshCw className="h-5 w-5 text-gray-400"/></button></div><div className="mt-5 space-y-4">{tickets.map(t=><article key={t.id} className="rounded-2xl border border-gray-800 bg-gray-950/50 p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-bold text-white">{t.subject}</h3><p className="font-mono text-xs text-blue-300">{t.deviceId}</p></div><span className="h-fit rounded-full bg-blue-500/10 px-3 py-1 text-xs font-bold text-blue-300">{t.status}</span></div><div className="mt-3 space-y-2">{t.messages?.map((m:any,i:number)=><div key={i} className="rounded-xl bg-gray-900 p-3 text-sm"><p className="text-xs text-gray-500">{m.authorEmail||m.role} · {new Date(m.createdAt).toLocaleString('hr-HR')}</p><p className="mt-1 text-gray-300">{m.message}</p></div>)}</div><div className="mt-3 flex gap-2"><input value={reply[t.id]||''} onChange={e=>setReply(r=>({...r,[t.id]:e.target.value}))} placeholder="Odgovor..." className="min-w-0 flex-1 rounded-lg border border-gray-700 bg-gray-900 p-2 text-sm text-white"/><button onClick={()=>update(t.id)} disabled={!reply[t.id]?.trim()} className="rounded-lg bg-blue-600 px-3 text-white disabled:opacity-40"><MessageSquare className="h-4 w-4"/></button>{userData?.role!=='subseller'&&t.status!=='resolved'&&<button onClick={()=>update(t.id,'resolved')} className="rounded-lg bg-emerald-700 px-3 text-xs font-bold text-white">Riješeno</button>}</div></article>)}{!tickets.length&&<p className="py-12 text-center text-gray-500">Nema otvorenih zahtjeva.</p>}</div></div></div>;
}
